sudo: required
dist: trusty
language: node_js

node_js:
   - node # will use latest node
sudo: required
before_script: # commands to run before the build step
  - npm install -g @angular/cli jest
  - npm install

notifications:
  email: # only receive email when the build status changes (someone broke the build!)
    on_failure: change
    on_success: change

cache:
  directories:
    - "node_modules"

stages:
  - test
  - build

test:
  - jest --runInBand --collectCoverage

build:
  - ng build --prod --base-href=multimapp/

deploy:
  local-dir: dist/
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master

