name: pull-request-actions
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
jobs:
  build-and-test:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install and build
        run: |
          npm install
          npm run build
      - name: Test
        run: |
          npm run test
